In [1]:
import numpy as np
import pandas as pd

In [2]:
arr = np.random.rand(3, 4)

In [3]:
arr

array([[ 0.75368315,  0.67554788,  0.50882728,  0.1409223 ],
       [ 0.77726951,  0.6770038 ,  0.54370774,  0.36513469],
       [ 0.37195289,  0.4839083 ,  0.46773128,  0.41800379]])

In [4]:
arr[1][3] = np.nan
arr

array([[ 0.75368315,  0.67554788,  0.50882728,  0.1409223 ],
       [ 0.77726951,  0.6770038 ,  0.54370774,         nan],
       [ 0.37195289,  0.4839083 ,  0.46773128,  0.41800379]])

In [5]:
df = pd.DataFrame(arr)
df

0         1         2         3
0  0.753683  0.675548  0.508827  0.140922
1  0.777270  0.677004  0.543708       NaN
2  0.371953  0.483908  0.467731  0.418004

In [6]:
pd.isna(df)

array([[False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False]], dtype=bool)